kdbus-y := \
	bus.o \
	connection.o \
	endpoint.o \
	fs.o \
	handle.o \
	item.o \
	main.o \
	match.o \
	message.o \
	metadata.o \
	names.o \
	node.o \
	notify.o \
	domain.o \
	policy.o \
	pool.o \
	reply.o \
	queue.o \
	util.o

obj-$(CONFIG_KDBUS) += kdbus.o
